development:
  adapter: postgresql
  encoding: unicode
  database: angular_rails_development
  pool: 5
  username: tomohung
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: angular_rails_test
  pool: 5
  username: tomohung
  password: 
